import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f4f9fc',
  },
  content: {
    padding: 14,
    gap: 12,
  },
  title: {
    fontSize: 21,
    fontWeight: '900',
    color: '#114b5f',
  },
  subtitle: {
    fontSize: 13,
    color: '#4e6974',
    marginTop: -2,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d6e3e8',
    padding: 12,
    gap: 8,
  },
  groupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  groupName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0b4b60',
  },
  expandText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2b6f85',
  },
  teamPreviewGrid: {
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  teamPreviewCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#d9e8ef',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: '#f8fbfd',
  },
  teamPreviewName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1d3640',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#edf3f6',
    paddingVertical: 6,
    gap: 8,
  },
  rowPos: {
    width: 18,
    fontSize: 12,
    color: '#62808a',
    fontWeight: '700',
  },
  rowTeam: {
    flex: 1,
    fontSize: 14,
    color: '#19323b',
    fontWeight: '700',
  },
  rowPoints: {
    width: 34,
    textAlign: 'right',
    fontSize: 14,
    color: '#114b5f',
    fontWeight: '900',
  },
  matchesWrap: {
    marginTop: 12,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: '#edf3f6',
    paddingTop: 10,
  },
  matchesTitle: {
    fontSize: 12,
    fontWeight: '900',
    color: '#0b4b60',
    marginBottom: 2,
  },
  matchCard: {
    backgroundColor: '#f8fbfd',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d9e8ef',
    padding: 12,
    marginBottom: 8,
    gap: 6,
  },
  teamRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  matchTeamFlag: {
    fontSize: 24,
  },
  matchTeam: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1d3640',
  },
  matchScore: {
    fontSize: 18,
    fontWeight: '900',
    minWidth: 20,
    textAlign: 'right',
  },
  matchDate: {
    fontSize: 10,
    color: '#4f6771',
    fontWeight: '600',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f4f9fc',
  },
});
