import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fffef9',
  },
  content: {
    padding: 16,
    paddingBottom: 30,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#2f2a24',
    marginBottom: 14,
    letterSpacing: 0.5,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  metricCard: {
    width: '48.5%',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
  },
  metricBlue: {
    backgroundColor: '#d6ecff',
    borderColor: '#8abfe8',
  },
  metricGreen: {
    backgroundColor: '#d9f7e8',
    borderColor: '#8ac8a9',
  },
  metricOrange: {
    backgroundColor: '#ffe5c2',
    borderColor: '#f0ba74',
  },
  metricCoral: {
    backgroundColor: '#ffd7d0',
    borderColor: '#e7a59a',
  },
  metricLabel: {
    fontSize: 12,
    color: '#3d3128',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricValue: {
    marginTop: 8,
    fontSize: 30,
    fontWeight: '900',
    color: '#1f1712',
  },
  bigCard: {
    marginTop: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cabca6',
    backgroundColor: '#f5eedf',
    padding: 14,
  },
  bigCardLabel: {
    color: '#584632',
    fontWeight: '800',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  bigCardValue: {
    marginTop: 6,
    color: '#281f16',
    fontWeight: '900',
    fontSize: 34,
  },
  sectionTitle: {
    marginTop: 18,
    marginBottom: 10,
    color: '#2f2a24',
    fontSize: 19,
    fontWeight: '900',
  },
  teamCard: {
    borderWidth: 1,
    borderColor: '#e2d4bf',
    borderRadius: 12,
    backgroundColor: '#fff7ea',
    padding: 12,
    marginBottom: 10,
  },
  teamRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  teamName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#3a2e22',
  },
  teamNumbers: {
    fontSize: 14,
    color: '#5d4b3a',
    fontWeight: '700',
  },
  progressTrack: {
    marginTop: 8,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#ecdcc3',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#f18805',
  },
  teamMeta: {
    marginTop: 7,
    fontSize: 12,
    color: '#5d4b3a',
    fontWeight: '600',
  },
  teamHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  expandIcon: {
    fontSize: 12,
    color: '#5d4b3a',
    marginRight: 8,
    fontWeight: '700',
  },
  teamRowExpand: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
  },
  stickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: '#fafaf5',
    borderRadius: 8,
    marginBottom: 10,
    marginTop: -4,
    marginLeft: -4,
    marginRight: -4,
  },
  stickerItem: {
    width: '31%',
    aspectRatio: 0.8,
  },
  stickerCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e2d4bf',
    overflow: 'hidden',
  },
  stickerSpecial: {
    backgroundColor: '#ffd700',
    borderColor: '#ffb700',
  },
  stickerNumber: {
    fontSize: 13,
    fontWeight: '900',
    color: '#3a2e22',
    textAlign: 'center',
  },
  stickerNumberMissing: {
    color: '#aaaaaa',
  },
  stickerName: {
    fontSize: 9,
    color: '#5d4b3a',
    fontWeight: '600',
    marginTop: 2,
    textAlign: 'center',
  },
  stickerImage: {
    width: '100%',
    height: '78%',
    backgroundColor: '#efe6d8',
  },
  stickerImageMissing: {
    opacity: 0.55,
    backgroundColor: '#d8d8d8',
    tintColor: '#9a9a9a',
  },
  stickerOwned: {
    borderColor: '#c8b89a',
  },
  stickerMissing: {
    borderColor: '#cccccc',
    backgroundColor: '#f5f5f5',
  },
  stickerFooter: {
    flex: 1,
    paddingHorizontal: 6,
    paddingVertical: 4,
    justifyContent: 'center',
  },
  cocaColaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#fff7ea',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2d4bf',
    marginBottom: 10,
    gap: 8,
  },
  cocaColaTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#c41e3a',
    flex: 1,
  },
  cocaColaCount: {
    fontSize: 12,
    fontWeight: '700',
    color: '#5d4b3a',
  },
  cocaColaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  cocaColaItem: {
    width: '48%',
  },
  cocaColaCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 100,
  },
  cocaColaName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1f1712',
    textAlign: 'center',
    marginBottom: 6,
  },
  rarityBadge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
    overflow: 'hidden',
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
  },
  modalCard: {
    width: '92%',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    paddingBottom: 14,
  },
  modalImage: {
    width: '100%',
    aspectRatio: 0.7,
    backgroundColor: '#e8dcc8',
  },
  modalTitle: {
    marginTop: 10,
    fontSize: 18,
    fontWeight: '900',
    color: '#2f2a24',
    textAlign: 'center',
  },
  modalSubtitle: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '600',
    color: '#5d4b3a',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
});
