import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fffef9',
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  backButton: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0b4b60',
    marginBottom: 12,
  },
  header: {
    marginBottom: 18,
  },
  title: {
    fontSize: 26,
    fontWeight: '900',
    color: '#2f2a24',
    letterSpacing: 0.3,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#6b5c4a',
    fontWeight: '600',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#9b8870',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 18,
    marginBottom: 8,
  },
  albumCard: {
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  albumCardInner: {
    padding: 14,
  },
  albumYear: {
    fontSize: 36,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  albumLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.9)',
    marginTop: 2,
  },
  albumMeta: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  albumChampion: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  albumChampionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  albumHost: {
    backgroundColor: 'rgba(0,0,0,0.18)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  albumHostText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
  },
  albumDescription: {
    marginTop: 10,
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '500',
    lineHeight: 18,
  },
  albumFooter: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  albumPageCount: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.7)',
  },
  albumButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  albumButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#ffffff',
  },
  albumButtonDisabled: {
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  albumButtonTextDisabled: {
    color: 'rgba(255,255,255,0.45)',
  },
  bonusBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255,215,0,0.9)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 4,
  },
  bonusBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#5a3e00',
  },
  extractHint: {
    marginTop: 24,
    padding: 14,
    backgroundColor: '#f0ece5',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d9cfc0',
  },
  extractHintTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#3a2e22',
    marginBottom: 6,
  },
  extractHintText: {
    fontSize: 12,
    color: '#5d4b3a',
    lineHeight: 18,
    fontFamily: 'monospace',
  },
});
